/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_SEMI = 2,
  anon_sym_PLUS_EQ = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_COMMA = 8,
  sym__quoted_string = 9,
  sym__non_quoted_string = 10,
  sym__number = 11,
  sym__semver_number = 12,
  sym__mixed_version = 13,
  sym__boolean = 14,
  sym_comment = 15,
  sym_source_file = 16,
  sym_package = 17,
  sym_pair = 18,
  sym__key = 19,
  sym__value = 20,
  sym_dictionary = 21,
  sym_list = 22,
  sym__elements = 23,
  sym_string = 24,
  sym_version = 25,
  sym_boolean = 26,
  aux_sym_dictionary_repeat1 = 27,
  aux_sym__elements_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [sym__quoted_string] = "_quoted_string",
  [sym__non_quoted_string] = "_non_quoted_string",
  [sym__number] = "_number",
  [sym__semver_number] = "_semver_number",
  [sym__mixed_version] = "_mixed_version",
  [sym__boolean] = "_boolean",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_package] = "package",
  [sym_pair] = "pair",
  [sym__key] = "_key",
  [sym__value] = "_value",
  [sym_dictionary] = "dictionary",
  [sym_list] = "list",
  [sym__elements] = "_elements",
  [sym_string] = "string",
  [sym_version] = "version",
  [sym_boolean] = "boolean",
  [aux_sym_dictionary_repeat1] = "dictionary_repeat1",
  [aux_sym__elements_repeat1] = "_elements_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym__quoted_string] = sym__quoted_string,
  [sym__non_quoted_string] = sym__non_quoted_string,
  [sym__number] = sym__number,
  [sym__semver_number] = sym__semver_number,
  [sym__mixed_version] = sym__mixed_version,
  [sym__boolean] = sym__boolean,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_package] = sym_package,
  [sym_pair] = sym_pair,
  [sym__key] = sym__key,
  [sym__value] = sym__value,
  [sym_dictionary] = sym_dictionary,
  [sym_list] = sym_list,
  [sym__elements] = sym__elements,
  [sym_string] = sym_string,
  [sym_version] = sym_version,
  [sym_boolean] = sym_boolean,
  [aux_sym_dictionary_repeat1] = aux_sym_dictionary_repeat1,
  [aux_sym__elements_repeat1] = aux_sym__elements_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym__quoted_string] = {
    .visible = false,
    .named = true,
  },
  [sym__non_quoted_string] = {
    .visible = false,
    .named = true,
  },
  [sym__number] = {
    .visible = false,
    .named = true,
  },
  [sym__semver_number] = {
    .visible = false,
    .named = true,
  },
  [sym__mixed_version] = {
    .visible = false,
    .named = true,
  },
  [sym__boolean] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_package] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__key] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_dictionary] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__elements] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_dictionary_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__elements_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_assignment = 1,
  field_key = 2,
  field_name = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assignment] = "assignment",
  [field_key] = "key",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_assignment, 1},
    {field_name, 0},
    {field_value, 2},
  [3] =
    {field_assignment, 1},
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
};

static const TSCharacterRange sym__non_quoted_string_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'$', '\''}, {'*', '*'}, {'-', ':'}, {'<', '<'}, {'>', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '"', 5,
        '#', 78,
        '(', 35,
        ')', 36,
        '+', 18,
        ',', 37,
        ';', 31,
        '=', 30,
      );
      if (lookahead == '\\') SKIP(28);
      if (lookahead == 'f') ADVANCE(19);
      if (lookahead == 't') ADVANCE(22);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '}') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 5,
        '#', 78,
        '(', 35,
        ')', 36,
        '\\', 53,
        'f', 44,
        't', 47,
        '{', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '+' &&
          lookahead != ',' &&
          lookahead != ';' &&
          lookahead != '=' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '#') ADVANCE(78);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(54);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 't') ADVANCE(47);
      if (lookahead == '{') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '+' &&
          lookahead != ',' &&
          lookahead != ';' &&
          lookahead != '=' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'a') ADVANCE(6);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 't') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'l') ADVANCE(8);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 's') ADVANCE(4);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(4);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'x') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'x') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '#') ADVANCE(78);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead == '}') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '+' &&
          lookahead != ',' &&
          lookahead != ';' &&
          lookahead != '=' &&
          lookahead != '{') ADVANCE(57);
      END_STATE();
    case 17:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '#') ADVANCE(78);
      if (lookahead == '\\') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '+' &&
          lookahead != ',' &&
          lookahead != ';' &&
          lookahead != '=' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 18:
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 25:
      if (lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 26:
      if (lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__quoted_string);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__quoted_string);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == ')') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(53);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 't') ADVANCE(47);
      if (lookahead == '{') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '+' &&
          lookahead != ',' &&
          lookahead != ';' &&
          lookahead != '=' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(54);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 't') ADVANCE(47);
      if (lookahead == '{') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '+' &&
          lookahead != ',' &&
          lookahead != ';' &&
          lookahead != '=' &&
          lookahead != '}') ADVANCE(57);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead == '}') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '+' &&
          lookahead != ',' &&
          lookahead != ';' &&
          lookahead != '=' &&
          lookahead != '{') ADVANCE(57);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '\\') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead == 'a') ADVANCE(46);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead == 'e') ADVANCE(77);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead == 'l') ADVANCE(48);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead == 'r') ADVANCE(49);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead == 's') ADVANCE(45);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead == 'u') ADVANCE(45);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if ((!eof && set_contains(sym__non_quoted_string_character_set_1, 10, lookahead))) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__non_quoted_string);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__number);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__number);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__number);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__number);
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '.') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__number);
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '-') ADVANCE(56);
      if (lookahead == '.') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__number);
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '.') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__number);
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '.') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__semver_number);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__semver_number);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__semver_number);
      if (lookahead == '"') ADVANCE(66);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__mixed_version);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__mixed_version);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__mixed_version);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__mixed_version);
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '.') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__mixed_version);
      if (lookahead == '"') ADVANCE(69);
      if (lookahead == '-') ADVANCE(56);
      if (lookahead == '.') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__mixed_version);
      if (lookahead == '"') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__boolean);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__boolean);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__boolean);
      if (lookahead == '"') ADVANCE(75);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(78);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym__quoted_string] = ACTIONS(1),
    [sym__number] = ACTIONS(1),
    [sym__semver_number] = ACTIONS(1),
    [sym__mixed_version] = ACTIONS(1),
    [sym__boolean] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(32),
    [sym_package] = STATE(27),
    [sym_string] = STATE(28),
    [sym__quoted_string] = ACTIONS(5),
    [sym__non_quoted_string] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__value] = STATE(20),
    [sym_dictionary] = STATE(20),
    [sym_list] = STATE(20),
    [sym__elements] = STATE(29),
    [sym_string] = STATE(20),
    [sym_version] = STATE(20),
    [sym_boolean] = STATE(20),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RPAREN] = ACTIONS(15),
    [sym__quoted_string] = ACTIONS(5),
    [sym__non_quoted_string] = ACTIONS(7),
    [sym__number] = ACTIONS(17),
    [sym__semver_number] = ACTIONS(19),
    [sym__mixed_version] = ACTIONS(21),
    [sym__boolean] = ACTIONS(23),
    [sym_comment] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym__value] = STATE(26),
    [sym_dictionary] = STATE(26),
    [sym_list] = STATE(26),
    [sym_string] = STATE(26),
    [sym_version] = STATE(26),
    [sym_boolean] = STATE(26),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RPAREN] = ACTIONS(25),
    [sym__quoted_string] = ACTIONS(5),
    [sym__non_quoted_string] = ACTIONS(7),
    [sym__number] = ACTIONS(17),
    [sym__semver_number] = ACTIONS(19),
    [sym__mixed_version] = ACTIONS(21),
    [sym__boolean] = ACTIONS(23),
    [sym_comment] = ACTIONS(9),
  },
  [STATE(4)] = {
    [sym__value] = STATE(26),
    [sym_dictionary] = STATE(26),
    [sym_list] = STATE(26),
    [sym_string] = STATE(26),
    [sym_version] = STATE(26),
    [sym_boolean] = STATE(26),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RPAREN] = ACTIONS(27),
    [sym__quoted_string] = ACTIONS(5),
    [sym__non_quoted_string] = ACTIONS(7),
    [sym__number] = ACTIONS(17),
    [sym__semver_number] = ACTIONS(19),
    [sym__mixed_version] = ACTIONS(21),
    [sym__boolean] = ACTIONS(23),
    [sym_comment] = ACTIONS(9),
  },
  [STATE(5)] = {
    [sym__value] = STATE(30),
    [sym_dictionary] = STATE(30),
    [sym_list] = STATE(30),
    [sym_string] = STATE(30),
    [sym_version] = STATE(30),
    [sym_boolean] = STATE(30),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [sym__quoted_string] = ACTIONS(5),
    [sym__non_quoted_string] = ACTIONS(7),
    [sym__number] = ACTIONS(17),
    [sym__semver_number] = ACTIONS(19),
    [sym__mixed_version] = ACTIONS(21),
    [sym__boolean] = ACTIONS(23),
    [sym_comment] = ACTIONS(9),
  },
  [STATE(6)] = {
    [sym__value] = STATE(26),
    [sym_dictionary] = STATE(26),
    [sym_list] = STATE(26),
    [sym_string] = STATE(26),
    [sym_version] = STATE(26),
    [sym_boolean] = STATE(26),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [sym__quoted_string] = ACTIONS(5),
    [sym__non_quoted_string] = ACTIONS(7),
    [sym__number] = ACTIONS(17),
    [sym__semver_number] = ACTIONS(19),
    [sym__mixed_version] = ACTIONS(21),
    [sym__boolean] = ACTIONS(23),
    [sym_comment] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      sym__quoted_string,
    ACTIONS(34), 1,
      sym__non_quoted_string,
    ACTIONS(37), 1,
      sym__number,
    ACTIONS(40), 1,
      sym__semver_number,
    ACTIONS(43), 1,
      sym__mixed_version,
    STATE(7), 2,
      sym_pair,
      aux_sym_dictionary_repeat1,
    STATE(24), 3,
      sym__key,
      sym_string,
      sym_version,
  [31] = 9,
    ACTIONS(5), 1,
      sym__quoted_string,
    ACTIONS(7), 1,
      sym__non_quoted_string,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(19), 1,
      sym__semver_number,
    ACTIONS(21), 1,
      sym__mixed_version,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_pair,
      aux_sym_dictionary_repeat1,
    STATE(24), 3,
      sym__key,
      sym_string,
      sym_version,
  [62] = 9,
    ACTIONS(5), 1,
      sym__quoted_string,
    ACTIONS(7), 1,
      sym__non_quoted_string,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym__number,
    ACTIONS(19), 1,
      sym__semver_number,
    ACTIONS(21), 1,
      sym__mixed_version,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    STATE(7), 2,
      sym_pair,
      aux_sym_dictionary_repeat1,
    STATE(24), 3,
      sym__key,
      sym_string,
      sym_version,
  [93] = 2,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(50), 6,
      anon_sym_RBRACE,
      sym__quoted_string,
      sym__non_quoted_string,
      sym__number,
      sym__semver_number,
      sym__mixed_version,
  [105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 5,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_PLUS_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [116] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 5,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_PLUS_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [127] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 5,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_PLUS_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [138] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 5,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_PLUS_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [149] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 5,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_PLUS_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [160] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    ACTIONS(58), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym__elements_repeat1,
  [173] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [191] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [200] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_RPAREN,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym__elements_repeat1,
  [213] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 3,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [231] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_RPAREN,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym__elements_repeat1,
  [244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 2,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
  [252] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_dictionary,
  [262] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
  [277] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_EQ,
  [284] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
  [291] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_SEMI,
  [298] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_SEMI,
  [305] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
  [312] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 31,
  [SMALL_STATE(9)] = 62,
  [SMALL_STATE(10)] = 93,
  [SMALL_STATE(11)] = 105,
  [SMALL_STATE(12)] = 116,
  [SMALL_STATE(13)] = 127,
  [SMALL_STATE(14)] = 138,
  [SMALL_STATE(15)] = 149,
  [SMALL_STATE(16)] = 160,
  [SMALL_STATE(17)] = 173,
  [SMALL_STATE(18)] = 182,
  [SMALL_STATE(19)] = 191,
  [SMALL_STATE(20)] = 200,
  [SMALL_STATE(21)] = 213,
  [SMALL_STATE(22)] = 222,
  [SMALL_STATE(23)] = 231,
  [SMALL_STATE(24)] = 244,
  [SMALL_STATE(25)] = 252,
  [SMALL_STATE(26)] = 262,
  [SMALL_STATE(27)] = 270,
  [SMALL_STATE(28)] = 277,
  [SMALL_STATE(29)] = 284,
  [SMALL_STATE(30)] = 291,
  [SMALL_STATE(31)] = 298,
  [SMALL_STATE(32)] = 305,
  [SMALL_STATE(33)] = 312,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__elements, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__elements, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dictionary_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 4, 0, 2),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__elements, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__elements, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__elements_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elements_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [93] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package, 4, 0, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_brazil_config(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "brazil_config",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
